FROM rabbitmq:4.2.4-management-alpine

RUN apk add --no-cache curl

# Используем флаги -L (follow redirect) и -f (fail on error)
# Ссылка ведет на прямой релиз плагина
RUN curl -Lf https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.2.0/rabbitmq_delayed_message_exchange-4.2.0.ez > $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange-4.2.0.ez

# Активируем плагин
RUN rabbitmq-plugins enable rabbitmq_delayed_message_exchange

# Удаляем curl после использования (опционально, для чистоты)
RUN apk del curl
