services:
  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: notifier
      POSTGRES_PASSWORD: notifier_pass
      POSTGRES_DB: notifier
    networks:
      - internal
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
networks:
  internal:
    driver: bridge