services:
  postgres:
    image: postgres:17
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-notifier}
      POSTGRES_PASSWORD:  ${DB_PASSWORD:-notifier_pass}
      POSTGRES_DB: ${DB_NAME:-notifier}
    networks:
      - notifier-network
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: notifier-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS:-guest}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notifier-network
  redis:
    image: redis:8.0.6-alpine3.21
    container_name: notifier-redis
    ports:
      - "6379:6379"
    networks:
      - notifier-network
  mailhog:
    image: mailhog/mailhog
    container_name: notifier-mailhog
    ports:
      - "1025:1025" # SMTP сервер (куда приложение шлет письма)
      - "8025:8025" # HTTP интерфейс (где вы смотрите письма)
    networks:
      - notifier-network
volumes:
  postgres:
networks:
  notifier-network:
    driver: bridge